// Licensed under either of Apache License, Version 2.0 or MIT license at your option.
// Copyright 2025 getlumos

//! Borsh Serialization Performance: LUMOS-Generated vs Manual
//!
//! Compares runtime performance of:
//! - Serialization speed (struct → bytes)
//! - Deserialization speed (bytes → struct)
//! - Binary size (bytes produced)
//! - Memory usage
//!
//! **Goal**: Prove LUMOS-generated code is equal or faster than hand-written Borsh

use borsh::{BorshDeserialize, BorshSerialize};
use criterion::{black_box, criterion_group, criterion_main, BenchmarkId, Criterion};

// ===== Manual Borsh Implementation (Hand-Written) =====

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug)]
pub struct ManualPlayer {
    pub wallet: [u8; 32], // Simulating PublicKey
    pub level: u16,
    pub experience: u64,
    pub equipped_items: Vec<[u8; 32]>,
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug)]
pub struct ManualMatchResult {
    pub player: [u8; 32],
    pub opponent: Option<[u8; 32]>,
    pub score: u64,
    pub timestamp: i64,
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug)]
pub enum ManualGameState {
    Active,
    Paused,
    Finished,
}

// ===== LUMOS-Generated Code (Same Structures) =====
// In real usage, this would be generated by `lumos generate`
// Here we simulate the output with identical Borsh derives

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug)]
pub struct LumosPlayer {
    pub wallet: [u8; 32],
    pub level: u16,
    pub experience: u64,
    pub equipped_items: Vec<[u8; 32]>,
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug)]
pub struct LumosMatchResult {
    pub player: [u8; 32],
    pub opponent: Option<[u8; 32]>,
    pub score: u64,
    pub timestamp: i64,
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug)]
pub enum LumosGameState {
    Active,
    Paused,
    Finished,
}

// ===== Test Data Generation =====

fn create_manual_player() -> ManualPlayer {
    ManualPlayer {
        wallet: [1u8; 32],
        level: 42,
        experience: 123456,
        equipped_items: vec![[2u8; 32], [3u8; 32], [4u8; 32]],
    }
}

fn create_lumos_player() -> LumosPlayer {
    LumosPlayer {
        wallet: [1u8; 32],
        level: 42,
        experience: 123456,
        equipped_items: vec![[2u8; 32], [3u8; 32], [4u8; 32]],
    }
}

fn create_manual_match_result() -> ManualMatchResult {
    ManualMatchResult {
        player: [1u8; 32],
        opponent: Some([2u8; 32]),
        score: 9999,
        timestamp: 1700000000,
    }
}

fn create_lumos_match_result() -> LumosMatchResult {
    LumosMatchResult {
        player: [1u8; 32],
        opponent: Some([2u8; 32]),
        score: 9999,
        timestamp: 1700000000,
    }
}

// ===== Serialization Benchmarks =====

fn bench_serialize_player(c: &mut Criterion) {
    let mut group = c.benchmark_group("serialize_player");

    let manual_player = create_manual_player();
    let lumos_player = create_lumos_player();

    group.bench_with_input(
        BenchmarkId::new("manual_borsh", "simple_struct"),
        &manual_player,
        |b, player| {
            b.iter(|| {
                let _bytes = borsh::to_vec(black_box(player)).unwrap();
            });
        },
    );

    group.bench_with_input(
        BenchmarkId::new("lumos_generated", "simple_struct"),
        &lumos_player,
        |b, player| {
            b.iter(|| {
                let _bytes = borsh::to_vec(black_box(player)).unwrap();
            });
        },
    );

    group.finish();
}

fn bench_deserialize_player(c: &mut Criterion) {
    let mut group = c.benchmark_group("deserialize_player");

    let manual_player = create_manual_player();
    let lumos_player = create_lumos_player();

    let manual_bytes = borsh::to_vec(&manual_player).unwrap();
    let lumos_bytes = borsh::to_vec(&lumos_player).unwrap();

    group.bench_with_input(
        BenchmarkId::new("manual_borsh", "simple_struct"),
        &manual_bytes,
        |b, bytes| {
            b.iter(|| {
                let _player: ManualPlayer = borsh::from_slice(black_box(bytes)).unwrap();
            });
        },
    );

    group.bench_with_input(
        BenchmarkId::new("lumos_generated", "simple_struct"),
        &lumos_bytes,
        |b, bytes| {
            b.iter(|| {
                let _player: LumosPlayer = borsh::from_slice(black_box(bytes)).unwrap();
            });
        },
    );

    group.finish();
}

// ===== Complex Type Benchmarks (Option) =====

fn bench_serialize_match_result(c: &mut Criterion) {
    let mut group = c.benchmark_group("serialize_match_result");

    let manual_result = create_manual_match_result();
    let lumos_result = create_lumos_match_result();

    group.bench_with_input(
        BenchmarkId::new("manual_borsh", "option_type"),
        &manual_result,
        |b, result| {
            b.iter(|| {
                let _bytes = borsh::to_vec(black_box(result)).unwrap();
            });
        },
    );

    group.bench_with_input(
        BenchmarkId::new("lumos_generated", "option_type"),
        &lumos_result,
        |b, result| {
            b.iter(|| {
                let _bytes = borsh::to_vec(black_box(result)).unwrap();
            });
        },
    );

    group.finish();
}

fn bench_deserialize_match_result(c: &mut Criterion) {
    let mut group = c.benchmark_group("deserialize_match_result");

    let manual_result = create_manual_match_result();
    let lumos_result = create_lumos_match_result();

    let manual_bytes = borsh::to_vec(&manual_result).unwrap();
    let lumos_bytes = borsh::to_vec(&lumos_result).unwrap();

    group.bench_with_input(
        BenchmarkId::new("manual_borsh", "option_type"),
        &manual_bytes,
        |b, bytes| {
            b.iter(|| {
                let _result: ManualMatchResult = borsh::from_slice(black_box(bytes)).unwrap();
            });
        },
    );

    group.bench_with_input(
        BenchmarkId::new("lumos_generated", "option_type"),
        &lumos_bytes,
        |b, bytes| {
            b.iter(|| {
                let _result: LumosMatchResult = borsh::from_slice(black_box(bytes)).unwrap();
            });
        },
    );

    group.finish();
}

// ===== Enum Benchmarks =====

fn bench_serialize_enum(c: &mut Criterion) {
    let mut group = c.benchmark_group("serialize_enum");

    let manual_states = vec![
        ManualGameState::Active,
        ManualGameState::Paused,
        ManualGameState::Finished,
    ];

    let lumos_states = vec![
        LumosGameState::Active,
        LumosGameState::Paused,
        LumosGameState::Finished,
    ];

    group.bench_function("manual_borsh", |b| {
        b.iter(|| {
            for state in &manual_states {
                let _bytes = borsh::to_vec(black_box(state)).unwrap();
            }
        });
    });

    group.bench_function("lumos_generated", |b| {
        b.iter(|| {
            for state in &lumos_states {
                let _bytes = borsh::to_vec(black_box(state)).unwrap();
            }
        });
    });

    group.finish();
}

// ===== Binary Size Comparison =====

fn bench_binary_size(c: &mut Criterion) {
    let manual_player = create_manual_player();
    let lumos_player = create_lumos_player();

    let manual_bytes = borsh::to_vec(&manual_player).unwrap();
    let lumos_bytes = borsh::to_vec(&lumos_player).unwrap();

    // Print size comparison (not a benchmark, just verification)
    println!("\n=== Binary Size Comparison ===");
    println!("Manual Borsh: {} bytes", manual_bytes.len());
    println!("LUMOS Generated: {} bytes", lumos_bytes.len());
    println!(
        "Difference: {} bytes",
        (lumos_bytes.len() as i64 - manual_bytes.len() as i64).abs()
    );

    assert_eq!(
        manual_bytes.len(),
        lumos_bytes.len(),
        "Binary sizes should be identical!"
    );

    // Benchmark the size calculation itself (trivial, but for completeness)
    c.bench_function("binary_size_calculation", |b| {
        b.iter(|| {
            let p = black_box(&manual_player);
            borsh::to_vec(p).unwrap().len()
        });
    });
}

// ===== Large Vec Benchmarks (Scalability) =====

fn bench_large_vec_serialization(c: &mut Criterion) {
    let mut group = c.benchmark_group("large_vec_serialization");

    // Create player with many equipped items
    let mut manual_player = create_manual_player();
    manual_player.equipped_items = vec![[255u8; 32]; 100]; // 100 items

    let mut lumos_player = create_lumos_player();
    lumos_player.equipped_items = vec![[255u8; 32]; 100];

    group.bench_function("manual_borsh_100_items", |b| {
        b.iter(|| {
            let _bytes = borsh::to_vec(black_box(&manual_player)).unwrap();
        });
    });

    group.bench_function("lumos_generated_100_items", |b| {
        b.iter(|| {
            let _bytes = borsh::to_vec(black_box(&lumos_player)).unwrap();
        });
    });

    group.finish();
}

// ===== Benchmark Groups =====

criterion_group!(
    borsh_comparison,
    bench_serialize_player,
    bench_deserialize_player,
    bench_serialize_match_result,
    bench_deserialize_match_result,
    bench_serialize_enum,
    bench_binary_size,
    bench_large_vec_serialization,
);

criterion_main!(borsh_comparison);
