import * as vscode from 'vscode';
import * as path from 'path';
import { LanguageClient, LanguageClientOptions, ServerOptions } from 'vscode-languageclient/node';

let client: LanguageClient | undefined;

export function activate(context: vscode.ExtensionContext) {
    console.log('LUMOS extension activated');

    // Register commands
    const generateCommand = vscode.commands.registerCommand('lumos.generate', async () => {
        const editor = vscode.window.activeTextEditor;
        if (!editor || editor.document.languageId !== 'lumos') {
            vscode.window.showErrorMessage('Not a LUMOS file');
            return;
        }

        const config = vscode.workspace.getConfiguration('lumos');
        const autoGenerate = config.get<boolean>('codeGeneration.autoGenerate', false);

        if (!autoGenerate) {
            const result = await vscode.window.showInformationMessage(
                'Generate Rust and TypeScript code from this schema?',
                'Yes', 'No'
            );
            if (result !== 'Yes') {
                return;
            }
        }

        // Execute lumos generate command
        const terminal = vscode.window.createTerminal('LUMOS');
        terminal.show();
        terminal.sendText(`lumos generate ${editor.document.fileName}`);
        vscode.window.showInformationMessage('Generating code...');
    });

    const validateCommand = vscode.commands.registerCommand('lumos.validate', async () => {
        const editor = vscode.window.activeTextEditor;
        if (!editor || editor.document.languageId !== 'lumos') {
            vscode.window.showErrorMessage('Not a LUMOS file');
            return;
        }

        // Execute lumos validate command
        const terminal = vscode.window.createTerminal('LUMOS');
        terminal.sendText(`lumos validate ${editor.document.fileName}`);
        vscode.window.showInformationMessage('Validating schema...');
    });

    context.subscriptions.push(generateCommand, validateCommand);

    // Auto-save generation (if enabled)
    const autoGenerateDisposable = vscode.workspace.onDidSaveTextDocument(async (document) => {
        if (document.languageId !== 'lumos') {
            return;
        }

        const config = vscode.workspace.getConfiguration('lumos');
        const autoGenerate = config.get<boolean>('codeGeneration.autoGenerate', false);

        if (autoGenerate) {
            const terminal = vscode.window.createTerminal('LUMOS');
            terminal.sendText(`lumos generate ${document.fileName}`);
        }
    });

    context.subscriptions.push(autoGenerateDisposable);

    // Show welcome message on first activation
    const hasShownWelcome = context.globalState.get('lumos.hasShownWelcome', false);
    if (!hasShownWelcome) {
        vscode.window.showInformationMessage(
            'LUMOS extension activated! Use Ctrl+Shift+P and search for "LUMOS" to see available commands.',
            'Got it'
        ).then(() => {
            context.globalState.update('lumos.hasShownWelcome', true);
        });
    }
}

export function deactivate() {
    if (client) {
        return client.stop();
    }
}
