// Auto-generated by LUMOS
// DO NOT EDIT - Changes will be overwritten

import * as borsh from '@coral-xyz/borsh';
import { PublicKey } from '@solana/web3.js';

export interface PlayerAccount {
  wallet: PublicKey;
  score: number;
  level: number;
  experience: number;
  last_login: number;
  is_active: boolean;
}

export const PlayerAccountSchema = borsh.struct([
  borsh.publicKey('wallet'),
  borsh.u64('score'),
  borsh.u16('level'),
  borsh.u64('experience'),
  borsh.i64('last_login'),
  borsh.bool('is_active'),
]);


export type GameEvent =
  | { kind: 'PlayerJoined'; field0: PublicKey }
  | { kind: 'ScoreUpdated'; player: PublicKey; score: number }
;

export const GameEventSchema = borsh.rustEnum([
  borsh.tuple([
    borsh.publicKey,
  ], 'PlayerJoined'),
  borsh.struct([
    borsh.publicKey('player'),
    borsh.u64('score'),
  ], 'ScoreUpdated'),
]);
