// Auto-generated by LUMOS
// DO NOT EDIT - Changes will be overwritten

use anchor_lang::prelude::*;
use solana_program::pubkey::Pubkey;

#[account]
pub struct PlayerAccount {
    pub wallet: Pubkey,
    pub score: u64,
    pub level: u16,
    pub experience: u64,
    pub last_login: i64,
    pub is_active: bool,
}

#[derive(AnchorSerialize, AnchorDeserialize, Debug, Clone)]
pub enum GameEvent {
    PlayerJoined(Pubkey),
    ScoreUpdated {
        player: Pubkey,
        score: u64,
    },
}
